### ISSUE TITLE
19.10: Evince has different names in Pop Shop

### ISSUE THREAD

**Issue by leviport** [pop-os/shop#136]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76@pop-os:~$ sudo apt update
[sudo] password for system76: 
Get:1 http://us.archive.ubuntu.com/ubuntu eoan InRelease [255 kB]
Hit:2 http://apt.pop-os.org/proprietary eoan InRelease                         
Hit:3 http://ppa.launchpad.net/system76/pop/ubuntu eoan InRelease              
Hit:4 http://us.archive.ubuntu.com/ubuntu eoan-security InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu eoan/universe Sources [9,696 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu eoan/universe i386 Packages [8,705 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages [8,816 kB]
Fetched 27.5 MB in 20s (1,350 kB/s)                                            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

**Issue/Bug Description:**
Evince (a default application in Pop) shows up with different names in Pop Shop. On a fresh 19.10 installation, it shows up as "Comic Books":
![evince-comic-books](https://user-images.githubusercontent.com/13512097/66847320-6dbbbe80-ef30-11e9-9d40-8839c7709e82.png)

And on my 19.10 install, it just shows up as "Evince":
![evince-my-machine-1910](https://user-images.githubusercontent.com/13512097/66847360-7b714400-ef30-11e9-97b0-3243d27b9c88.png)

**Steps to reproduce (if you know):**
Search "Evince" in Pop Shop, or look through your installed applications.

**Expected behavior:**
It is named "PDF Documents" in a fresh 19.04 installation:
![evince-1904](https://user-images.githubusercontent.com/13512097/66847502-b6737780-ef30-11e9-8eb8-29cdf4661534.png)

**Other Notes:**

**Comment by BootlegPhil** [comment]
This issue appears to have been fixed, from what I can tell. Are you still affected by this?

**Comment by leviport** [comment]
I'm still seeing it on clean installs, but it seems to correct itself after installing updates. With 20.04 on the horizon, I'll close this issue if it becomes irrelevant.
