### ISSUE TITLE
The Network Settings Button Doesn't Work

### ISSUE THREAD

**Issue by ghost** [pop-os/shop#149]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_Shop

**Issue/Bug Description:**
When I turn off the Wi-Fi and go to the Pop Shop, a message comes up and a button labelled Network Settings is present on the Pop Shop window. When I push the button, nothing happens.

**Steps to reproduce (if you know):**
Turn off the Wi-Fi.

Go to the Pop Shop.

Attempt to click on the Network Settings button which appears on the Shop window.

**Expected behavior:**
The button should pull up the Wi-Fi menu in Settings.

**Comment by cassidyjames** [comment]
This (or something like it) is required for it to work: github.com/cassidyjames/settings-shim

**Comment by BootlegPhil** [comment]
> This (or something like it) is required for it to work: [@cassidyjames/settings-shim](https://github.com/cassidyjames/settings-shim)

How would I install this on Pop?

**Comment by cassidyjames** [comment]
Well, ideally that would be installed as a part of Pop!_OS. I updated the readme with developer-oriented build instructions.

**Comment by 13r0ck** [comment]
This issue still exists

https://user-images.githubusercontent.com/58987761/140997789-e5596175-00e1-4244-a563-74bea9a6e8c2.mp4
